import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import Slides from './Slides';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const [showSlides, setShowSlides] = useState(false);
  const [currentSlide, setCurrentSlide] = useState(0);  

  const handleSlideClick = () => {
    if (currentSlide < 14) {
      setCurrentSlide(currentSlide + 1);
    } else {
      setShowSlides(false);
      setCurrentSlide(0);
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by Javier Trombetta" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description} style={{ justifyContent: 'flex-end' }}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            By{' '}
            <motion.div 
              animate={{ scale: [1, 1.05, 1] }}
              transition={{ duration: 3, repeat: Infinity }}
            >
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </motion.div>
          </a>
        </div>

        <div className={styles.center} onClick={handleSlideClick}>
          <AnimatePresence>
            {!showSlides ? (
              <motion.div 
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ duration: 5 }}
                onClick={() => setShowSlides(true)}
                style={{ cursor: 'pointer' }}
              >
                <Image
                  className={styles.logo}
                  src="/next.svg"
                  alt="Next.js Logo"
                  width={180}
                  height={37}
                  priority
                />
              </motion.div>
            ) : (
                <div style={{ position: 'relative', width: '100%', height: '100%' }}>
                  <Slides currentSlide={currentSlide} />         
                </div>
            )}
          </AnimatePresence>
        </div>     

        {!showSlides && (
          <div className={styles.grid}>          
            <a
              href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
            >
              <h2>
                Aprendé <span>-&gt;</span>
              </h2>
              <p>
              ... sobre Next.js en un curso interactivo con cuestionarios
              </p>
            </a>

            <a
              href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
            >
              <h2>
                Descubrí <span>-&gt;</span>
              </h2>
              <p>
                ... e implementá proyectos repetitivos de ejemplo de Next.js
              </p>
            </a>

            <a
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
            >
              <h2>
                Desplegá <span>-&gt;</span>
              </h2>
              <p>
              ... instantáneamente un sitio Next.js
              </p>
            </a>
            <a
              href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
            >
              <h2>
                Conocé más <span>-&gt;</span>
              </h2>
              <p>
                ... sobre sus características y la API de Next.js
              </p>
            </a>
          </div>
        )}
      </main>
    </>
  )
}
